name: Release

on:
  push:
    branches: [master]

jobs:
  build-release:
    environment: PROD
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x"]
        os: [ubuntu-latest]
    env:
      CI: 1 # prevents extra Cypress installation progress messages
      HUSKY: 0 # disables husky hooks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_SEMANTIC_RELEASE_PAT }}

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1

      - name: Start Deploy Message
        uses: Basis-Theory/github-actions/deploy-slack-action@master
        with:
          slack-api-token: ${{ secrets.SLACK_DUCKBOT_API_KEY }}
          channel: ${{ vars.SLACK_DUCKBOT_RELEASE_CHANNEL_ID }}

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Write .env
        run: make write-lib-vars
        env:
          ENVIRONMENT: prod
          DD_GIT_SHA: ${{ github.sha }}

      - name: Build
        run: make build
        env:
          SKIP_INSTALL: 1 # install with cache was done already

      - name: Create dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Release
        run: make release
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: us-east-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          ENVIRONMENT: prod
          GITHUB_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::469828239459:role/github-actions-admin-prod
          aws-region: us-east-2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::469828239459:role/terraform-admin
          aws-region: us-east-2
          role-chaining: true

      - name: UAT Deploy Index Hash
        run: make deploy-index-hash
        env:
          AWS_REGION: us-east-2
          ENVIRONMENT:  prod

      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ vars.CF_PROD_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_PURGE_TOKEN }}
          PURGE_URLS: '["https://js.basistheory.com/*"]'

      # - name: Purge prod wl cache
      #   uses: jakejarvis/cloudflare-purge-action@master
      #   env:
      #     CLOUDFLARE_ZONE: ${{ vars.CF_PROD_ELEMENTS_ZONE_ID }}
      #     CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_PURGE_TOKEN }}

      - name: Stop Deploy Message
        if: always()
        uses: Basis-Theory/github-actions/deploy-slack-action@master
        with:
          slack-api-token: ${{ secrets.SLACK_DUCKBOT_API_KEY }}
          channel: ${{ vars.SLACK_DUCKBOT_RELEASE_CHANNEL_ID }}
          status: "done"

  release-to-uat:
    environment: UAT
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Client dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::244923700941:role/github-actions-admin-uat
          aws-region: us-east-2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::244923700941:role/terraform-admin
          aws-region: us-east-2
          role-chaining: true

      - name: UAT Deploy Index Hash
        run: make deploy-index-hash
        env:
          AWS_REGION: us-east-2
          ENVIRONMENT:  uat

      # - name: Purge uat cache
      #   uses: jakejarvis/cloudflare-purge-action@master
      #   env:
      #     CLOUDFLARE_ZONE: ${{ vars.CF_UAT_ZONE_ID }}
      #     CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_PURGE_TOKEN }}
      #     PURGE_URLS: '["https://js.btsandbox.com/*"]'

      # - name: Purge uat wl cache
      #   uses: jakejarvis/cloudflare-purge-action@master
      #   env:
      #     CLOUDFLARE_ZONE: ${{ vars.CF_UAT_ELEMENTS_ZONE_ID }}
      #     CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_PURGE_TOKEN }}